services:
  app:
    image: evershop/evershop:latest
    restart: always
    environment:
      DB_HOST: mydb-postgres-proxy.proxy-cdi00kw8glaz.ap-southeast-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_PASSWORD: "*fJ8U#5~*><zx6JuS)V?KYJadqwA"
      DB_USER: dbadmin
      DB_NAME: master
    networks:
      - myevershop
    depends_on:
      - database
    ports:
      - 443:3000

  # The postgres database: 
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - myevershop

networks:
  myevershop:
    name: MyEverShop
    driver: bridge

volumes:
  postgres-data: